name: Render PlantUML Diagrams

on:
  push:
    paths:
      - 'docs/**/*.puml'
  workflow_dispatch:  # allows manual run from Actions tab

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Download PlantUML Jar
        run: |
            curl -L -o plantuml.jar  https://github.com/plantuml/plantuml/releases/download/v1.2024.4/plantuml-1.2024.4.jar

      - name: Render PlantUML Diagrams
        run: |
          mkdir -p docs/rendered
          find docs -name "*.puml" -exec java -jar plantuml.jar -tpng {} -o docs/rendered \;

      - name: Upload Rendered Diagrams
        uses: actions/upload-artifact@v4
        with:
          name:
